# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recall < Formula
  desc "100% offline command intelligence for your terminal — eliminate Command Amnesia"
  homepage "https://github.com/Om-Rohilla/recall"
  version "1.0.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Om-Rohilla/recall/releases/download/v1.0.16/recall_1.0.16_macOS_x86_64.tar.gz"
      sha256 "9d5e925ecacf5eaa5d7ca1d02eb7f1c8c96eacd80d470af2b2440d062e87de9e"

      define_method(:install) do
        bin.install "recall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Om-Rohilla/recall/releases/download/v1.0.16/recall_1.0.16_macOS_arm64.tar.gz"
      sha256 "0fdd74f8514c6ad2ca96429d7cb87617274478477a99404c2b506765578a7360"

      define_method(:install) do
        bin.install "recall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Om-Rohilla/recall/releases/download/v1.0.16/recall_1.0.16_linux_x86_64.tar.gz"
      sha256 "b3ea943ee37c50311c604aeba5db58ca73d394a41bff84aa6e3267647b51af52"
      define_method(:install) do
        bin.install "recall"
      end
    end
  end

  test do
    system "#{bin}/recall", "--help"
  end
end
